CREATE TABLE nyc_airbnb (
  id SERIAL PRIMARY KEY,
  name TEXT,
  host_id INTEGER,
  last_scraped DATE,
  neighborhood_group TEXT,
  neighborhood TEXT,
  latitude REAL,
  longitude REAL,
  room_type TEXT,
  price SMALLINT,
  minimum_nights SMALLINT,
  number_of_reviews SMALLINT,
  number_of_reviews_ltm SMALLINT,
  host_response_time TEXT,
  host_response_rate REAL,
  host_has_profile_pic SMALLINT,
  property_type TEXT,
  bedrooms REAL,
  bathrooms REAL,
  private_bath SMALLINT,
  description TEXT,
  accommodates SMALLINT,
  amenities TEXT[],
  availability_365 SMALLINT,
  maximum_nights INTEGER,
  review_scores_rating DOUBLE PRECISION,
  review_scores_cleanliness DOUBLE PRECISION,
  review_scores_value DOUBLE PRECISION,
  review_scores_communication DOUBLE PRECISION,
  instant_bookable SMALLINT
)